### DISCUSSION TITLE
how to implement autoresize for md-editor-v3

### DISCUSSION THREAD

**Discussion by tidusvn05** [imzbf/md-editor-v3#568] [Q&A] [answered]
similar textarea start with 1 line
when enter new line will expand size larger

**Comment by imzbf** [comment, marked as answer]
You can set the height to automatic, for example:

```css
.md-editor {
  height: auto;
  min-height: 94px;
}
```
