### ISSUE TITLE
Text overflow is handled incorrectly for english text and cannot be modified

### ISSUE THREAD

**Issue by hwgn** [imzbf/md-editor-v3#109]
Right now, when text reaches the end of the line it will break immediately and without hyphen:

![image](https://user-images.githubusercontent.com/19843204/170971498-9bc29b8b-d55e-4954-bc9a-ee48d3bf2696.png)

Setting css style of the `Editor` component sadly does not fix this, so it would need to be done internally. Tested using this class:

```css
.hyphenate {
  word-wrap: break-word;
  overflow-wrap: break-word;

  -webkit-hyphens: auto;
  -moz-hyphens: auto;
  hyphens: auto;
}
```

**Comment by imzbf** [comment]
Default `break-all`, keeps width of each line consistent. To override it:

```css
.md-content .md-preview,
.md-content .md-html {
  word-break: break-word;
}
```
