### ISSUE TITLE
能够修改预览状态下的字体大小吗？

### ISSUE THREAD

**Issue by 15958185146** [imzbf/md-editor-v3#115]
我的p标签默认字体大小是14px,但是使用了ma-editor后，就变成了16px，修改了依赖里面的css style，好像也没有起到作用，该如何解决呢

**Comment by imzbf** [comment]
```css
.md-content .md-preview,
.md-content .md-html {
  font-size: 14px;
}
```
