### ISSUE TITLE
Dealing with CSS class conflict (md-editor-v3 & Quasar)?

### ISSUE THREAD

**Issue by ajmas** [imzbf/md-editor-v3#160]
I am trying to use this component with [Quasar](https://quasar.dev/), but the `md` class of the component is conflicting with the `md` class provided by Quasar:

```css
.lg-hide, .xs, .lt-sm, .sm, .lt-md, .md, .lt-lg, .gt-lg, .xl {
    display: none !important;
}
```
Are there any suggestions on how to work around this?
