### ISSUE TITLE
修改有序列表的 token 問題

### ISSUE THREAD

**Issue by kenkoedu** [imzbf/md-editor-v3#242]
# 問題
我的目標是想把 markdown 的有序數列改成
```
(a)
(b)
    (i)
    (ii)
(c)
```
等等

我用了以下兩個方法都不成功

# 方法一：使用 renderer
```javascript
MdEditor.config({
  markedRenderer(renderer) {
    renderer.list = (body, ordered, start) => {
      return ordered ? `<ol type='a'>${body}<ol>` : `<ul>${body}<ul>`;
    };
    return renderer;
  }
});
```

結果是 HTML 成功產出 `<ol type="a">`
![image](https://user-images.githubusercontent.com/51295510/232559723-87d2e617-7f27-443d-920a-50ebf5839324.png)

但預覽欄無法渲染
![image](https://user-images.githubusercontent.com/51295510/232559947-306d38e7-3d81-4a62-963e-db0330e06f9f.png)

# 方法二：修改 css
`editor.vue`
```vue
<script setup>
import "../styles/list.css"
</script>
```

`list.css`
```css
.default-theme ol{
    list-style-type: lower-alpha;
}
```

我發現預覽會自動跳過相關操作，例如
`list.css`
```css
.default-theme ol{
    color: red;
}
```
是會正常地顯示紅色字

但 `list-style-type` 就會自動跳過

請問是否我的編程有誤，或者有其他東西阻礙？
謝謝

**Comment by imzbf** [comment]
这个不需要定义`renderer`，修改css失败是因为选择器的优先级低于了组件默认的

组件定义列表样式的代码在[这里](https://github.com/imzbf/markdown-theme/blob/develop/src/common/index.scss#L60)

可以知道，是直接定义的`li`标签，所以你的样式没有生效

你可以这样做：

```css
.default-theme ol > li {
    list-style-type: lower-alpha;
}

.default-theme ol > li > ol > li {
    list-style-type: lower-roman;
}
```
