### ISSUE TITLE
wrong word brakes

### ISSUE THREAD

**Issue by blockiyt** [imzbf/md-editor-v3#511]
### Describe the issue

The text is previewed with cutoff words (wrong word breaks), not like in the input.

![Bildschirmfoto 2024-05-09 um 16 13 04](https://github.com/imzbf/md-editor-v3/assets/65811753/420d8a51-6c03-4ae5-98d3-f67b1e3a6c81)

Is there a way to fix this? I couldn't find anything in the docs.

### Procedure version

latest

**Comment by imzbf** [comment]
Just adjust the style of the content area

```css
.md-editor-preview p {
    word-break: break-word;
}
```
