### ISSUE TITLE
预览模式下有序和无序列表无法正常显示

### ISSUE THREAD

**Issue by sunaccess** [imzbf/md-editor-v3#533]
### Describe the issue

我使用的是Naive UI，在编辑预览和仅预览都无法正常显示有序和无序列表，请问怎么解决
![Snipaste_2024-05-22_11-50-49](https://github.com/imzbf/md-editor-v3/assets/4462119/26be88e2-a577-44b8-abc1-c9f4bb36b208)

### Procedure version

md-editor-v3 4.15.2

**Comment by imzbf** [comment]
https://github.com/imzbf/md-editor-v3/issues/521#issuecomment-2107471494

**Comment by 0604hx** [comment]
我也碰到过同样的问题，是因为 vant、tailwind 样式的配置：
```css
ol, li {
    list-style: none;
}
```
可以手动修正：
```css
.md-editor-preview {
    ol, li {
        list-style: disc !important;
    }
}
```
