### ISSUE TITLE
编辑器选中颜色背景色如何修改

### ISSUE THREAD

**Issue by linyuanjie** [imzbf/md-editor-v3#640]
### Describe the issue

编辑器选中颜色背景色看起来很淡，不容易区分选中和没有选中的差别，如何修改选中的背景颜色
![image](https://github.com/user-attachments/assets/85802d39-adb9-4eec-a0a9-505ecf02f424)

### Procedure version

"md-editor-v3": "^4.18.0",

**Comment by imzbf** [comment]
用css覆盖

```css
.cm-selectionBackground,
.cm-content::selection {
  background-color: red !important;
}
```
