### ISSUE TITLE
catalog主题切换后出现位移

### ISSUE THREAD

**Issue by Plusto** [imzbf/md-editor-v3#673]
### 描述这个Bug

点击主题切换后，catalog出现位移
![image](https://github.com/user-attachments/assets/27d96937-47c0-4da4-88c2-bb73accbcf61)
![image](https://github.com/user-attachments/assets/8a9ca836-4d40-42e5-9e20-5b5775ebb08d)
原因应该是前后padding不一致
![image](https://github.com/user-attachments/assets/abc76366-97ad-4457-819e-761d6cb693b2)
![image](https://github.com/user-attachments/assets/5a384c1f-7bb6-4e2e-8f97-54eb7032ee5e)
都改成padding:5px,8px后问题会消失

### 版本号

vscode，chrome

**Comment by Plusto** [comment]
https://fauc3t.top/?#/article/Collection/1
朋友的网页，点击右上主体切换按钮就会一直动来动去的

**Comment by Jay-716** [comment]
似乎是因为[这两个padding](https://github.com/imzbf/md-editor-v3/blob/260e7bb80673a2d5da694ea9866c65078e5f22c3/packages/MdCatalog/index.less#L24-L30)不一样。
```less
.@{prefix}-catalog {
  & > &-link {
    padding: 5px 8px;
  }

  &-link {
    padding: 5px 0 5px 1em;
    line-height: 1.2;
...
```
