### ISSUE TITLE
MdPreview组件无序列表和有序列表前缀不显示

### ISSUE THREAD

**Issue by kramrs** [imzbf/md-editor-v3#714]
### 描述这个Bug

编辑状态下
![image](https://github.com/user-attachments/assets/9f76bb41-25d8-4bef-bc8a-24a5eef54bd2)
预览状态下
![image](https://github.com/user-attachments/assets/4e99b1fc-0120-41ac-a45d-bb2552a998c2)

### 版本号

chrome 130.0.6723.117

**Comment by xiaochen0517** [comment]
如果使用 `tailwindcss` 导致的问题，可以使用下面的 `css` 解决。

```css
@layer base {
  ul {
    list-style-type: disc;
  }

  ol {
    list-style-type: decimal;
  }
}
```
