### ISSUE TITLE
如何设置工具栏还有展示的内容的大小？

### ISSUE THREAD

**Issue by xiaojian152194** [imzbf/md-editor-v3#749]
### Describe the issue

如何设置工具栏还有展示的内容的大小？
![Snipaste_2025-01-10_15-53-43](https://github.com/user-attachments/assets/9add72f8-9b44-4531-92ee-28de353b7eeb)
这个太小了

### Procedure version

5.2.1

**Comment by imzbf** [comment]
只能样式覆盖，覆盖图标的大小就行了，下面是自带的大小

```css
svg.md-editor-icon {
    height: 16px;
    padding: 4px;
    width: 16px;
    fill: none;
    display: block;
    overflow: hidden;
}
```
