### ISSUE TITLE
不知道为什么，我的工具栏图标按钮，变得超级无敌小。

### ISSUE THREAD

**Issue by charlestang** [imzbf/md-editor-v3#775]
### 描述这个Bug

<img width="881" alt="Image" src="https://github.com/user-attachments/assets/c7cae750-1325-43ae-9e4b-0d501cfdf631" />

如上截图所示。

然后我看这个样式里，有个 padding 4px。

<img width="176" alt="Image" src="https://github.com/user-attachments/assets/35c8ce6e-2c72-45de-b35b-2143d3cb30ef" />

### 版本号

5.2.3

**Comment by fda93** [comment]
应该是设置了全局样式
```css
* {
  box-sizing: border-box;
}
```
添加样式
``` css
.md-editor svg {
  box-sizing: content-box;
}
```

**Comment by Hiram-Wong** [comment]
可以设置
```css
svg.md-editor-icon {
    height: 24px;
    width: 24px;
  }
```

**Comment by charlestang** [comment]
> 应该是设置了全局样式
> 
> * {
>   box-sizing: border-box;
> }
> 添加样式
> 
> .md-editor svg {
>   box-sizing: content-box;
> }

谢谢大佬，你说得对，我在组件里添加了一个样式：

```css
:deep(.md-editor svg) {
  box-sizing: content-box;
}
```
解决问题了！
