### ISSUE TITLE
能否暴露内部 border属性 和 Background-Color属性

### ISSUE THREAD

**Issue by Super1Windcloud** [imzbf/md-editor-v3#789]
### 一个很棒的想法

  能否暴露内部 border属性 和 Background-Color属性  , 真的很需要这个功能

**Comment by imzbf** [comment]
https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%A7%99%E2%80%8D%E2%99%82%EF%B8%8F%20%E8%B0%83%E6%95%B4%E7%BC%96%E8%BE%91%E5%99%A8%E6%A0%B7%E5%BC%8F

这里定义了css变量

**Comment by Super1Windcloud** [comment]
@imzbf 
  # Background-Color 是 可以 ,但是文本颜色 Color 似乎无法覆盖 

```CSS
<style scoped>
.md-editor-dark  {
  --md-bk-color:  transparent ;
  background-color: transparent ;
  border-color:   transparent ;
  font-style: normal;
  color : ghostwhite !important;
 
  font-synthesis: style;
   text-decoration: none  ;
  font-family: "Cascadia Mono",serif;
 }

</style>
``` 

![Image](https://github.com/user-attachments/assets/68eef83b-1d55-41f0-b42b-c1880d738d72)
