### ISSUE TITLE
关于代码块渲染上下不对称的问题

### ISSUE THREAD

**Issue by kifuan** [imzbf/md-editor-v3#87]
补充: 这个"不对称"指的是上下留白的区域
多行代码显示效果看不大出来, 但是单行代码渲染出来会发现上下不对称

![-1](https://user-images.githubusercontent.com/61240774/166423972-290ca424-14dd-4636-ba03-ee74238a7788.png)

为了验证这个看法, 我做了下面这些操作

![1](https://user-images.githubusercontent.com/61240774/166423873-4c6b1bd5-109a-41ba-9dbd-c3fa010b0c5a.png)
![2](https://user-images.githubusercontent.com/61240774/166424006-fb060cd0-f466-45af-9848-ff9b317c4431.png)

可以看出, 他们的高度是不一样的, 我也从JS里面获取了一下
![3](https://user-images.githubusercontent.com/61240774/166424417-dcadbab7-ff12-4350-a40e-c4b6ecb40699.png)

如果说我把外面这一层的高度设置成里面这一层, 那么这个问题可以在一定程度上解决

![7](https://user-images.githubusercontent.com/61240774/166424893-466b848d-8595-4c97-931c-2158a8f4143b.png)

但同时代码块右侧也会出现滚动条.

我这里只是从调试的角度来看待这个问题, 至于如何在框架内部解决我还没有具体的思路

**Comment by imzbf** [comment]
看起来像是之前的版本更新代码块的结构，`line-height`没有给对正确的元素，如果现在影响很大的话，在你的项目中暂时添加一下`css`覆盖：

```css
pre > code {
line-height: initial !important;
}

.code-block {
line-height: 1.6rem !important ;
}

```

**Comment by kifuan** [comment]
可以解决! 这里放一组对比图

这是什么改动都没有

![image](https://user-images.githubusercontent.com/61240774/166447726-823fd038-f856-48b5-98e9-6f611fad7019.png)

这是第一次修改后

![image](https://user-images.githubusercontent.com/61240774/166447622-fc4b1924-414e-4ef5-afcf-f8dad35263f9.png)

通过选中所有子元素可以修正行号的问题

```css
pre > code {
    line-height: initial !important;
}

pre > code > * {
    line-height: 1.6rem !important;
}
```

这是最终结果

![image](https://user-images.githubusercontent.com/61240774/166447669-d05a14e1-b28b-41da-b9ea-f37223f4de8c.png)
